export const TRANSLATION_STRINGS = {
  loginScreen: 'loginScreen',
  enterUserName: 'enterUserName',
  English: 'English',
  Arabic: 'عربي',
  enterPassword: 'enterPassword',
  error: 'error',
  emailError: 'emailError',
  passwordError: 'passwordError',
  logout: 'logout',
  moviesLabel: 'movies',
  timeoutError: 'Request timed out',
  noInternet: 'noInternet',
  logoutAlert: 'logoutAlert',
  cancel: 'cancel',
  ok: 'ok',
};
